-- # Assigment 3 # -- 

-- CREATE DATABASE EMPLOYEE;
-- USE EMPLOYEE; 

-- TO IMPORT TABLES FROM CSV FILE:
-- FROM THE OBJECT EXPLORER NAVIGATE TO:
-- EMPLOYEE --> TASKS --> IMPORT FLAT FILE
-- IMPORT EMP.CSV AND EMP_SAL.CSV
-- TO CONFIRM THE IMPORT UNCOMMENT AND RUN:

SELECT *
FROM EMP;

SELECT *
FROM EMP_SAL;

-----------------------

-- ADDING CONSTRAINS AT EMP 
----ADD CONSTRAINT ON EID AS PRIMARY KEY (FOR PRIMARY KEY NOT NULL IS MANDATORY )----
ALTER TABLE EMP 
ALTER COLUMN EID CHAR(5) NOT NULL;

ALTER TABLE EMP 
ADD CONSTRAINT EID_PK PRIMARY KEY(EID);

ALTER TABLE EMP
ALTER COLUMN NAME VARCHAR(50) NOT NULL;

ALTER TABLE EMP 
ADD CONSTRAINT ADRESS_CK CHECK (
                               ADDR NOT LIKE ('%UTTAM NAGAR%') 
                                         OR 
                               ADDR NOT LIKE('UTTAM NAGAR%') 
                                         OR 
                               ADDR NOT LIKE('%UTTAM NAGAR')
                               );

ALTER TABLE EMP 
ADD CONSTRAINT CITY_CK CHECK (
                               CITY IN ('DELHI','GURGAON','BELGUM', 'CHENNAI', 'NAGPUR', 'NOIDA')
                               );

ALTER TABLE EMP 
ADD CONSTRAINT PHONE_UN UNIQUE(PHONE);

ALTER TABLE EMP 
ADD CONSTRAINT EMAIL_CK CHECK (
    EMAIL LIKE ('%GMAIL.COM') 
    OR EMAIL LIKE ('%YAHOO.COM')
    OR EMAIL LIKE ('%HOTMAIL.COM')
    OR EMAIL LIKE ('%OUTLOOK.COM')
);

ALTER TABLE EMP 
ADD CONSTRAINT DOB_CK CHECK (DOB <= '2000-01-01');


-- ADDING CONSTRAINTS AT EMP_SAL 
ALTER TABLE EMP_SAL 
ADD CONSTRAINT FK_EID_EMPSAL FOREIGN KEY (EID) REFERENCES EMP(EID);

ALTER TABLE EMP_SAL 
ADD CONSTRAINT DEPT_CK CHECK (DEPT IN ('HR', 'MIS', 'OPS', 'IT', 'ADMIN', 'TEMP'));

ALTER TABLE EMP_SAL 
ADD CONSTRAINT DESI_CK CHECK (DESI IN ('ASSOCIATE', 'TEMP', 'VP', 'MANAGER', 'DIRECTOR'));

ALTER TABLE EMP_SAL
ADD CONSTRAINT SALARY_CK CHECK (SALARY >= 15000);

ALTER TABLE EMP_SAL 
ADD CONSTRAINT DEPT_DF DEFAULT 'TEMP' FOR DEPT;

