-- ## Assigment 6 ## --

-- USE EMPLOYEE;

CREATE VIEW EMP_SAL_DETAILS
AS
    SELECT EMP.EID, NAME, DOJ AS 'DATE OF JOIN',
        DEPT AS 'DEPARTMENT', DESI AS 'DESIGNATION',
        SALARY AS 'BASIC', SALARY*0.15 AS 'HRA',
        SALARY*0.9 AS 'PF',
        (SALARY + (SALARY*0.15) + (SALARY*0.9)) AS 'NET SALARY',
        ((SALARY + (SALARY*0.15) + (SALARY*0.9)) - (SALARY*0.9)) AS 'GROSS SALARY'
    FROM EMP
        INNER JOIN EMP_SAL
        ON EMP.EID = EMP_SAL.EID;

-- CHECKING THE CREATED VIEW 
SELECT *
FROM EMP_SAL_DETAILS

CREATE VIEW DISPLAY_DETAILS
AS
    SELECT EMP.EID, NAME, DOJ AS 'DATE OF JOIN',
        DESI AS 'DESIGNATION', DEPT AS 'DEPARTMENT'
    FROM EMP
        INNER JOIN EMP_SAL
        ON EMP.EID = EMP_SAL.EID
    WHERE DESI LIKE ('MANAGER') AND DOJ LIKE ('2019%');

--  CHECKING THE CREATED VIEW 

SELECT * FROM DISPLAY_DETAILS

CREATE VIEW SALARY_DETAILS_TEAMWISE
AS 
  SELECT CITY,DEPT AS 'DEPARTMENT', COUNT(EMP_SAL.EID) AS 'TEAM MEMBERS',
         SUM(SALARY) AS 'TOTAL SALARY', AVG(SALARY) AS 'AVERAGE SALARY'
  FROM EMP_SAL 
  JOIN EMP 
  ON EMP_SAL.EID = EMP.EID 
  GROUP BY DEPT, CITY;

-- CHECKING THE CREATED VIEW 
SELECT * FROM SALARY_DETAILS_TEAMWISE;

