-- # Assigment 4 # --

-- USE EMPLOYEE;

SELECT CITY, COUNT(EID) AS 'COUNT OF EMPLOYEE'
FROM EMP
GROUP BY CITY
ORDER BY 'COUNT OF EMPLOYEE' DESC;

SELECT *
FROM EMP
WHERE EMAIL NOT LIKE ('%YAHOO%');

SELECT DESI, SUM(SALARY) AS 'TOTAL COST', COUNT(EID) AS 'NUMBER OF EMPLOYEE'
FROM EMP_SAL
GROUP BY DESI
ORDER BY  'TOTAL COST' DESC;
