-- # Assigment 7 # --

-- USE EMPLOYEE;

CREATE FUNCTION CALCULATOR (@NUM1 AS INT, @NUM2 AS INT, @OPERATOR AS CHAR(1))
RETURNS INT 
AS 
BEGIN
    DECLARE @R AS INT

    IF @OPERATOR = '+'
        SET @R = @NUM1 + @NUM2;
    ELSE IF @OPERATOR = '-'
        SET @R = @NUM1 - @NUM2 ;
    ELSE IF @OPERATOR = '*'
        SET @R = @NUM1 * @NUM2 ;
    ELSE IF @OPERATOR = '/' AND @NUM2 != 0
        SET @R = @NUM1 / @NUM2 ;
    ELSE 
        SET @R = NULL ;

    RETURN @R
END;

-- CHECKING THE CREATED FUNCTION 
SELECT DBO.CALCULATOR (12,6,'*') AS 'RESULT';

-------------------------------------------------------------------------


CREATE FUNCTION CORPORATE_MAIL (@NAME AS VARCHAR(20), @ID AS CHAR(5))
RETURNS CHAR(13)
AS
BEGIN
    DECLARE @EMAIL AS CHAR(13)

    SET @EMAIL = CONCAT(LEFT(@NAME, 1), 
				        LEFT(RIGHT(@NAME, 
						CHARINDEX(' ' ,@NAME)), 1),
						RIGHT(@ID, 3), '@RCG.COM')

    RETURN @EMAIL
END;

--CHECKING THE CREATED FUNCTION 
SELECT DBO.CORPORATE_MAIL('MUSTAKIM KURESHI','E2596') AS 'CORPORATE MAIL';

-------------------------------------------------------------------------

CREATE FUNCTION EMP_DEPARTMENT (@DEPT AS VARCHAR(20))
RETURNS TABLE 
AS 
     RETURN (SELECT EMP.EID, NAME, DESI, DEPT, SALARY
FROM EMP
    INNER JOIN EMP_SAL
    ON EMP.EID = EMP_SAL.EID
WHERE DEPT = @DEPT);

--CHECKING CREATED FUNCTION 
SELECT *
FROM DBO.EMP_DEPARTMENT('IT')

-------------------------------------------------------------------------

CREATE FUNCTION CURR_BDY()
RETURNS TABLE 
AS 
    RETURN (SELECT NAME, DEPT, DESI, CITY
FROM EMP
    INNER JOIN EMP_SAL
    ON EMP.EID = EMP_SAL.EID
WHERE MONTH(DOB) = MONTH(GETDATE()));


-- CHECKING THE CREATED FUNCTION 
SELECT *
FROM CURR_BDY();

-------------------------------------------------------------------------

CREATE FUNCTION COMPLETED_5YR()
RETURNS TABLE 
AS 
    RETURN (SELECT NAME, DEPT, DOJ
FROM EMP
    INNER JOIN EMP_SAL
    ON EMP.EID = EMP_SAL.EID
WHERE DATEDIFF(YY,DOJ,GETDATE()) >= 5 );

--CHECKING THE CREATED FUNCTION 
SELECT *
FROM COMPLETED_5YR()