-- # Assigment 5 # -- 

-- USE EMPLOYEE;

SELECT EMP.EID, NAME, CITY, DOJ, DEPT, DESI, SALARY
FROM EMP
    INNER JOIN EMP_SAL
    ON EMP.EID = EMP_SAL.EID
WHERE CITY = 'DELHI';

SELECT EMP.EID, NAME, ADDR1, ADDR2, CITY, PHONE, EMAIL, DOB, DOJ
FROM EMP
    LEFT JOIN EMP_SAL
    ON EMP.EID = EMP_SAL.EID
WHERE SALARY IS NULL; 

